- apiVersion: v1
  kind: Service
  metadata:
    name: html-app
    namespace: env-dev
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    selector:
      app: html-app
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: html-app
    namespace: env-dev
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: html-app
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: html-app
      spec:
        containers:
          - image: 'qedzone/html-app:${trigger[''tag'']}'
            name: html-app
            ports:
              - containerPort: 80
                name: http
                protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 100Mi